import type { Metadata } from "next"

import { ThemeProvider } from "@/components/theme-provider"

import "./globals.css"

import { Inter } from "next/font/google"
import { Nav } from "@/components/ui/header/Nav"
import { Footer } from "@/components/ui/footer/Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app"
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`flex flex-col max-w-6xl mx-auto h-screen px-2 ${inter.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
        >
          <header className="border-b-2 border-cascade-400">
            <Nav />
          </header>
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
